name: upgrading
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/coming-soon-icon.png
    - assets/images/consultation-icon.png
    - assets/images/video-preparation-icon.png
  
